In [4]:
!pip install scipy
!pip install numpy

# Punto 1 a.

In [9]:
import numpy as np


X = np.array([[1],[0],[0]])
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

## Compute difference in stopping condition
## Assign Y = AX to avoid computing AX multiple times
Y = A@X
difference = Y - np.linalg.norm(Y)*X

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X = Y
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    Y = A@X
    difference = Y - np.linalg.norm(Y)*X
    
    m = m + 1
    
print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue is approximately:")
print(np.linalg.norm(Y),'\n')
print("Magnitude of the difference is:")
print(np.linalg.norm(difference))

Eigenvector is approximately:
[[ 0.7071088 ]
 [ 0.        ]
 [-0.70710476]] 

Magnitude of the eigenvalue is approximately:
12.000008583030988 

Magnitude of the difference is:
2.5749255655705085e-05


In [12]:
import numpy as np

X = np.array([[1],[0],[0]])
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])

m = 0
while (m < 20):
    X = A@X
    X = X/np.linalg.norm(X)
    m = m + 1
print(X)


print(np.linalg.norm(A@X))

[[ 0.70710678]
 [ 0.        ]
 [-0.70710678]]
12.000000000002048


# Punto1 b.
El resultado al cambiar el miu aproxima a 12, ya que este valor aproxima al autovalor más próximo, si pusieramos un valor cercano a 6 como 7.5, aproxima a 6 o un valor cercano a 3, como puede ser 4, este aproxima a 3

In [23]:
import scipy.linalg as sla


X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100
difference = X

A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
I = np.eye(3)
mu = 10
Shifted_A = A-mu*I
LU_factorization = sla.lu_factor(Shifted_A)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Eigenvalue of A is approximately:")
print(np.linalg.norm(A@X))


Eigenvector is approximately:
[[-7.07113254e-01]
 [-1.94211789e-05]
 [ 7.07100308e-01]] 

Eigenvalue of A is approximately:
11.999972530202639


# Punto 1 c. 


In [51]:
import scipy.linalg as sla


X = np.array([[1],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100
difference = X

A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
I = np.eye(3)
mu = 7.5
Shifted_A = A-mu*I
LU_factorization = sla.lu_factor(Shifted_A)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Eigenvalue of A is approximately:")
print(np.linalg.norm(A@X))


Eigenvector is approximately:
[[ 1.]
 [ 0.]
 [-0.]] 

Eigenvalue of A is approximately:
10.816653826391969


# Punto 2 a.
Utilizando de las potencias, hallamos que el valor mayor es 36, y utilizando el método de inverso de potencia obtenemos que el valor menor, es 4.

Utilizando como mui -20, por ser el valor en el medio y la pista que nos dieron de que el último valor era negativo, hallamos que el último autovalor es -8

In [55]:
import numpy as np


X = np.array([[1],[0],[0]])
A = np.array([[-2,-18,6],[-11,3,11],[-27,15,31]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

## Compute difference in stopping condition
## Assign Y = AX to avoid computing AX multiple times
Y = A@X
difference = Y - np.linalg.norm(Y)*X

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X = Y
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    Y = A@X
    difference = Y - np.linalg.norm(Y)*X
    
    m = m + 1
    
print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue is approximately:")
print(np.linalg.norm(Y),'\n')
print("Magnitude of the difference is:")
print(np.linalg.norm(difference))

Eigenvector is approximately:
[[5.56674896e-07]
 [3.16227933e-01]
 [9.48683242e-01]] 

Magnitude of the eigenvalue is approximately:
35.99998451019761 

Magnitude of the difference is:
2.5699366771184847e-05


In [54]:
X = np.array([[1],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

difference = X
A = np.array([[-2,-18,6],[-11,3,11],[-27,15,31]])
A_inv = np.linalg.inv(A)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = A_inv@X
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1
    
print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue of A inverse is approximately:")
print(np.linalg.norm(A_inv@X),'\n')
print("Magnitude of the eigenvalue of A is approximately:")
print(np.linalg.norm(A@X),'\n')

Eigenvector is approximately:
[[7.07117570e-01]
 [2.15781986e-05]
 [7.07095992e-01]] 

Magnitude of the eigenvalue of A inverse is approximately:
0.24998283458260934 

Magnitude of the eigenvalue of A is approximately:
3.999450712928783 



In [111]:
import scipy.linalg as sla

X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.001
MAX_ITERATIONS = 1000
difference = X

A = np.array([[-2,-18,6],[-11,3,11],[-27,15,31]])
I = np.eye(3)
mu = -20
Shifted_A = A-mu*I
LU_factorization = sla.lu_factor(Shifted_A)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Eigenvalue of A is approximately:")
print(np.linalg.norm(A@X))

Eigenvector is approximately:
[[0.81649641]
 [0.4086473 ]
 [0.40784922]] 

Eigenvalue of A is approximately:
8.01172724864646


In [100]:
eigenvalues, eigenvectors = sla.eig( np.array([[-2,-18,6],[-11,3,11],[-27,15,31]]))

# Punto 2 b.
Validamos con la librería scipy

In [93]:
eigenvalues

array([36.+0.j, -8.+0.j,  4.+0.j])

In [94]:
eigenvectors

array([[-3.69683191e-16, -8.16496581e-01,  7.07106781e-01],
       [-3.16227766e-01, -4.08248290e-01,  3.78720551e-16],
       [-9.48683298e-01, -4.08248290e-01,  7.07106781e-01]])